addon/mongocrypt.cc, src/index.ts
See the ticket for motivation/why it would be convenient to have this earlier than the 'main' range V2 work 🙂 
No
Testing
Porting change from: https://github.com/mongodb/libmongocrypt/pull/809
A new option `rangeV2` can be passed to the MongoCrypt constructor to enable the new protocol. It is marked expiremental because it will likely be removed in a future release, this is for testing only.
=> fix(NODE-6173): add rangeV2 feature flag toggle to Node.js bindings

.github/docker/Dockerfile.glibc, .github/scripts/libmongocrypt.mjs, .github/workflows/build.yml, .gitignore, package.json
- We now download a prebuild of libmongocrypt instead of building from source.
- `--build`, `-b` will still build from source
No
Now we do not need to have cmake or other toolchain requirements satisfied for libmongocrypt only what is needed for the bindings.
=> chore(NODE-6186): add downloading to FLE build script

.github/scripts/libmongocrypt.mjs, .github/workflows/build.yml
- remove exists function
no
Checking if something exists before doing a FS action on it risks race condition. 
We don't use exists and we shouldn't add it back in. cleanup.
=> chore: remove unused `exists` function

addon/mongocrypt.cc, src/index.ts, test/bindings.test.ts
All references to `rangepreview` have been renamed to `range`.  Additionally, the feature flag for range v2 has been removed (confirmed with Kenn that supporint v1 is no longer necessary).
=> feat(NODE-5908): support range v2 protocol

.github/actions/setup/action.yml, .github/actions/sign_and_upload_package/action.yml, .github/workflows/build.yml
- Adds signing to the native bundle tarballs and uploads them to the Github release.
- Uploads the detached signatures for the tarballs to the Github release.
- Adds release please to the Github apps builds.
- Publishes the release with provenance.
None
NODE-6160
=> chore(NODE-6160): sign and upload to releases

.github/workflows/build.yml, release-please-config.json
- Changing configurations so the next release is an alpha
Not here, will update the release documentation in the driver.
- https://github.com/mongodb/node-mongodb-native/blob/main/etc/notes/releasing.md
Testing automated releases with a prerelease
=> chore: prepare for alpha release

.github/scripts/libmongocrypt.mjs, .github/workflows/build.yml, README.md, binding.gyp
- We build one universal binary on macos-latest
- Copy the tar file to have an x64 name for prebuild's sake
No
- Stop using macos 11 because it will be removed soon
=> feat(NODE-6226): build macos universal binary

.github/scripts/libmongocrypt.mjs
- Build typescript at the end of building the bindings
No
The build script runs npm install like so:
```js
await run('npm', ['install', '--ignore-scripts']);
```
creates a prebuild, then finishes.
Because of `'--ignore-scripts'` it doesn't run the prepare lifecycle hook, so typescript isn't compiled. 
=> chore: add typescript compilation to build script

.github/docker/Dockerfile.glibc, .github/workflows/build.yml, .github/workflows/lint.yml, test/release.test.ts
- Change linux build OS to ubunut bionic making glibc requirement 2.27+
No
Compatibility with RHEL 8
=> fix(NODE-6237): build against glibc 2.27

.github/scripts/libmongocrypt.mjs, README.md, binding.gyp
When building a static library version of this package we omit the arch flags since you only need to build for your current system.
=> fix(MONGOSH-1808): static building on intel macs and windows

.github/workflows/build.yml, .github/workflows/release_6.1.yml, release-please-config.json
- Remove releasing from pull_request workflow
- Remove prerelease from config, do not tag npm package with alpha
No
Proper release incoming :rocket:
=> chore: prepare for non-prerelease

addon/mongocrypt.cc, addon/mongocrypt.h, package.json, test/bindings.test.ts, test/crypto.test.ts
MakeExplicitEncryptionContext takes an option, `expressionMode`, that controls whether an expression context or regular context is instantiated.  This option is always provided by the driver, is required by TS but in C++ we coerce the option to boolean instead.
This PR aligns the C++ to match the intended behavior.
=> fix(NODE-6300): make expressionMode required in C++ in makeExplicitEncryptionContext

package.json
Just waiting on https://spruce.mongodb.com/task/libmongocrypt_release_publish_upload_all_9a88ac5698e8e3ffcd6580b98c247f0126f26c40_24_08_01_18_30_17/logs?execution=0.
- Support `range` algorithm as stable.
See the [libmongocrypt release here](https://github.com/mongodb/libmongocrypt/releases/tag/1.11.0)
=> feat(NODE-6307): use libmongocrypt 1.11.0

.github/workflows/release_6.1.yml
=> chore: switch to releasing from main

.github/dependabot.yml
Adds dependabot config to update Github Actions.
Adds dependabot config to update Github Actions.
None
NODE-6568
=> chore(NODE-6568): add dependabot for github actions

.github/docker/Dockerfile.glibc, .github/workflows/test.yml, .mocharc.json, package-lock.json, package.json, src/index.ts
=> fix(NODE-6591): remove bindings as a dependency

addon/mongocrypt.cc, addon/mongocrypt.h, package.json, src/index.ts
Exposes methods required to retry KMS requests and enables them in libmongocrypt.
- Set the flag to retry KMS requests.
- Adds uSleep property and fail method.
- Bumps libmongocrypt to 1.12.
None
NODE-6695
Retrying KMS requests is now enabled and the new method `uSleep` and `fail` property are now exposed to handle the feature in the driver.
=> feat(NODE-6695): enable KMS retry protocol

addon/mongocrypt.cc
Fail is a method not a property. This is a quick fix.
None
=> fix: set fail as instance method

.github/docker/Dockerfile.glibc, .github/scripts/get-commit-from-ref.sh, .github/scripts/libmongocrypt.mjs, .github/scripts/utils.mjs
Improvements to the `libmongocrypt.mjs` script.  Primarily, this PR makes libmongocrypt's download much faster by only downloading binaries for the current platform, instead of a single tarball containing all binaries for all platforms.
I also reorganized the scripts a bit.
=> chore(NODE-6726): make install libmongocrypt script faster

.github/scripts/libmongocrypt.mjs, addon/mongocrypt.cc, package.json, src/index.ts
- Upgrade to libmongocrypt 1.13.
- Add option to enable mongocrypt_setopt_enable_multiple_collinfo.
Calls `mongocrypt_setopt_enable_multiple_collinfo` to enable the setting
=> feat(NODE-6773): add multiple collinfo option

addon/mongocrypt.cc, package.json, src/index.ts, test/unit/bindings.test.ts
Adds the option `keyExpirationMS` to set the DEK cache expiration time.
- Adds the `keyExpirationMS` option to the TS types.
- Sets the option if provided when constructing a MongoCrypt.
- Updates libmongocrypt to 1.14
None
NODE-6947
A new option, `keyExpirationMS` can now be provided to set the new value. The default is 60000
```ts
import { MongoCrypt } from 'mongodb-client-encryption';
const crypt = new MongoCrypt({ keyExpirationMS: 100000 });
```
=> feat(NODE-6947): add keyExpirationMS to bindings

.github/dependabot.yml
Adding a prod-dependencies group to the dependabot config
N/A
Convenience of dependency updates
=> chore: Update dependabot.yml to allow prod dependencies

addon/mongocrypt.cc, src/index.ts
=> feat(NODE-7216)! remove support for enableMultipleCollInfo

.eslintrc.json, src/bindings.ts, src/index.ts, test/bundling/webpack/src/index.ts, test/unit/bindings.test.ts, test/unit/error_wrapper.test.ts, test/unit/index.test.ts, test/unit/release.test.ts
This PR adds support for a custom error-wrapping function in the bindings.  The function is used to wrap any error that is thrown from the C++ bindings.  This is accomplished by subclassing the classes exported from our C++ bindings with wrappers that try-catch any errors thrown from C++.
This PR has [a corresponding driver PR](https://github.com/mongodb/node-mongodb-native/pull/4694) that uses the error wrapper to wrap errors in a MongoCryptError.
Patch against driver: https://spruce.mongodb.com/version/68daedb19fc9d800072eb762/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> feat(NODE-7043): add support for custom error wrapping functions

src/bindings.ts, src/index.ts
CryptoCallbacks are being removed from the driver in v7, so we no longer need to support them as an option in the MongoCrypt constructor.
=> feat(NODE-6297)!: Remove support for explicitly providing CryptoCallbacks
